### ISSUE TITLE
[Bug] Cast from PG::Numeric to (Float64 | Nil) failed.

### ISSUE THREAD

**Issue by zw963** [luckyframework/avram#1038]
Please check following runable script.

```crystal
require "pg"
require "avram"

class AppDatabase < Avram::Database
end

AppDatabase.configure do |settings|
  settings.credentials = Avram::Credentials.new(database: "test_db", username: "postgres", hostname: "localhost")
end

Avram.configure do |settings|
  settings.database_to_migrate = AppDatabase
  settings.lazy_load_enabled = true
end

class CreateFoo::V20240420041991 < Avram::Migrator::Migration::V1
  def migrate
    create table_for(Foo), if_not_exists: true do
      primary_key id : Int64
      add number : Float64, precision: 10, scale: 5
      add_timestamps
    end
  end

  def rollback
    drop table_for(Foo)
  end
end

Avram::Migrator::Runner.drop_db(true)
Avram::Migrator::Runner.create_db(true)
Avram::Migrator::Runner.new.run_next_migration

abstract class BaseModel < Avram::Model
  def self.database : Avram::Database.class
    AppDatabase
  end
end

class Foo < BaseModel
  table do
    column number : Float64?
  end
end

Foo::SaveOperation.create!(number: 70884.70074)
Foo::SaveOperation.create!(number: 50530.49889)
Foo::SaveOperation.create!(number: 37639.3706)
Foo::SaveOperation.create!(number: 18688.18317)

query = Foo::BaseQuery.new

query.number.select_min
```

It will raise a exception like this:

```
Unhandled exception: Cast from PG::Numeric to (Float64 | Nil) failed.
  from lib/avram/src/avram/queryable.cr:305:5 in 'select_min'
  from test.cr:54:1 in '__crystal_main'
  from /home/zw963/Crystal/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /home/zw963/Crystal/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /home/zw963/Crystal/share/crystal/src/crystal/main.cr:141:3 in 'main'
  from ???
```
But, i consider it should work:

```
 ╰─ $ psql
psql (16.2)
Type "help" for help.

zw963=# \c college_development
You are now connected to database "college_development" as user "zw963".
college_development=# select max(universities.ranking_2023_min) from universities;
     max
-------------
 42972.42460
(1 row)

```

I saw several issues related to this, but, it's seem like not fixed yet?

## version info:

pg:  0.28.0
avram: 1.2.0

**Comment by jwoertink** [comment]
This doesn't look like a bug. You created your column in the migration as `Float` 

```
add number : Float64, precision: 10, scale: 5
```

Then in your model, you said it was `Float | Nil`

```
column number : Float64?
```

All `Float` columns are stored as `PG::Numeric` in the database, so it's trying to convert your `PG::Numeric` to `Float | Nil` as your model has, but the type should be `Float`.

**Comment by zw963** [comment]
Hi, same issue when change the column type to Float64? 

```crystal
require "pg"
require "avram"

class AppDatabase < Avram::Database
end

AppDatabase.configure do |settings|
  settings.credentials = Avram::Credentials.new(database: "test_db", username: "postgres", hostname: "localhost")
end

Avram.configure do |settings|
  settings.database_to_migrate = AppDatabase
  settings.lazy_load_enabled = true
end

class CreateFoo::V20240420041991 < Avram::Migrator::Migration::V1
  def migrate
    create table_for(Foo), if_not_exists: true do
      primary_key id : Int64
      add number : Float64?, precision: 10, scale: 5
      add_timestamps
    end
  end

  def rollback
    drop table_for(Foo)
  end
end

Avram::Migrator::Runner.drop_db(true)
Avram::Migrator::Runner.create_db(true)
Avram::Migrator::Runner.new.run_next_migration

abstract class BaseModel < Avram::Model
  def self.database : Avram::Database.class
    AppDatabase
  end
end

class Foo < BaseModel
  table do
    column number : Float64?
  end
end

Foo::SaveOperation.create!(number: 70884.70074)
Foo::SaveOperation.create!(number: 50530.49889)
Foo::SaveOperation.create!(number: 37639.3706)
Foo::SaveOperation.create!(number: 18688.18317)
Foo::SaveOperation.create!(number: 18688.18317)

query = Foo::BaseQuery.new

query.number.select_min
```

**Comment by zw963** [comment]
Hi, how to the newest changes on main branch in a exists lucky project?

Following is my shards.yml

```yaml
---
name: college
version: 0.1.0
targets:
  college:
    main: src/college.cr
crystal: '>= 1.12.1'
dependencies:
  lucky:
    github: luckyframework/lucky
    version: ~> 1.2.0
  avram:
    github: luckyframework/avram
    version: ~> 1.2.0
  carbon:
    github: luckyframework/carbon
    version: ~> 0.5.1
  carbon_sendgrid_adapter:
    github: luckyframework/carbon_sendgrid_adapter
    version: ~> 0.5.0
  lucky_env:
    github: luckyframework/lucky_env
    version: ~> 0.2.0
  lucky_task:
    github: luckyframework/lucky_task
    version: ~> 0.3.0
  authentic:
    github: luckyframework/authentic
    version: '>= 1.0.0, < 2.0.0'
  jwt:
    github: crystal-community/jwt
    version: ~> 1.6.0
  baked_file_system_mounter:
    github: crystal-china/baked_file_system_mounter
development_dependencies:
  lucky_flow:
    github: luckyframework/lucky_flow
    version: ~> 0.10.0
```

I get error like this when i run `shards update`.

```sh
 ╰─ $ shards update
Resolving dependencies
Fetching https://github.com/luckyframework/lucky.git
Fetching https://github.com/luckyframework/avram.git
Fetching https://github.com/luckyframework/carbon_sendgrid_adapter.git
Fetching https://github.com/luckyframework/carbon.git
Fetching https://github.com/luckyframework/lucky_env.git
Fetching https://github.com/luckyframework/lucky_task.git
Fetching https://github.com/luckyframework/authentic.git
Fetching https://github.com/crystal-community/jwt.git
Fetching https://github.com/crystal-china/baked_file_system_mounter.git
Fetching https://github.com/luckyframework/lucky_flow.git
Unable to satisfy the following requirements:

- `avram (branch main)` required by `shard.yml`
- `avram (>= 1.0.0)` required by `authentic 1.0.0`
Failed to resolve dependencies
```

**Comment by jwoertink** [comment]
@zw963 You need to create a new `shards.override.yml` file with

```yml
dependencies:
  avram:
    github: luckyframework/avram
    branch: main
```

**Comment by zw963** [comment]
> @zw963 You need to create a new `shards.override.yml` file with
> 
> ```yaml
> dependencies:
>   avram:
>     github: luckyframework/avram
>     branch: main
> ```

Sorry, i paste the wrong file, following is my shards.yml, it not work.

```yaml
---
name: college
version: 0.1.0
targets:
  college:
    main: src/college.cr
crystal: '>= 1.12.1'
dependencies:
  lucky:
    github: luckyframework/lucky
    version: ~> 1.2.0
  avram:
    github: luckyframework/avram
    branch: main
  carbon:
    github: luckyframework/carbon
    version: ~> 0.5.1
  carbon_sendgrid_adapter:
    github: luckyframework/carbon_sendgrid_adapter
    version: ~> 0.5.0
  lucky_env:
    github: luckyframework/lucky_env
    version: ~> 0.2.0
  lucky_task:
    github: luckyframework/lucky_task
    version: ~> 0.3.0
  authentic:
    github: luckyframework/authentic
    version: '>= 1.0.0, < 2.0.0'
  jwt:
    github: crystal-community/jwt
    version: ~> 1.6.1
  baked_file_system_mounter:
    github: crystal-china/baked_file_system_mounter
development_dependencies:
  lucky_flow:
    github: luckyframework/lucky_flow
    version: ~> 0.10.0
```

the diff is:

```diff
diff --git a/shard.yml b/shard.yml
index 7735200..208b9bf 100644
--- a/shard.yml
+++ b/shard.yml
@@ -11,7 +11,7 @@ dependencies:
     version: ~> 1.2.0
   avram:
     github: luckyframework/avram
-    version: ~> 1.2.0
+    branch: main
   carbon:
     github: luckyframework/carbon
     version: ~> 0.5.1
@@ -29,7 +29,7 @@ dependencies:
     version: '>= 1.0.0, < 2.0.0'
   jwt:
     github: crystal-community/jwt
-    version: ~> 1.6.0
+    version: ~> 1.6.1
   baked_file_system_mounter:
     github: crystal-china/baked_file_system_mounter
 development_dependencies:
```

Get same error as above.

I consider, add `shards.override.yml` same as change `shards.yml` directly, right?
